#!/bin/bash

# INFO: Author: Geordy Jomon
# A script that copies a file to TMPDIR (or /tmp) for editing
# and uses fswatch to sync changes when the file is saved on macOS.

if ! command -v fswatch &>/dev/null; then
  echo "Error: fswatch is not installed. Please install it using 'brew install fswatch'."
  exit 1
fi

if [ -z "$1" ]; then
  printf "Temp edit: Edit files in TMPDIR\nUsage: .%s <file_path>\n\nTMPDIR=%s\n" "$0" "$TMPDIR"
  exit 1
fi

orginal_file_path="$1"
temp_file_path="${TMPDIR:-/tmp}/$(basename "${orginal_file_path}")"

if ! cp "$orginal_file_path" "$temp_file_path"; then
  printf "Temp Edit:\nError: Failed to copy the file to the temporary directory."
  exit 1
fi

"${EDITOR:-vim}" "$temp_file_path" &

editor_pid=$!

fswatch -o "$temp_file_path" | while read; do
  if ! cp "$temp_file_path" "$orginal_file_path"; then
    printf "Temp Edit:\nWarning: Failed to sync the file back to the original location."
  fi
done &

wait "$editor_pid"

if ! cp "$temp_file_path" "$orginal_file_path"; then
  echo "Error: Failed to copy the final version back to the original location."
  exit 1
fi

echo "Temp Edit: File edited and synced successfully."
